version: 2
jobs:
  py-3.7: &build-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}
      - run:
          # Install dependencies with --user to enable easier caching
          name: Install dependencies
          command: |
            pip install -r requirements.txt --user
            pip install -e '.[d]'
            pip install codecov --user
            /home/circleci/.local/bin/codecov
      - run:
          name: Test code is well formatted
          command: |
            /home/circleci/.local/bin/black --target-version=py36 xlson tests --check --quiet || (echo 'The source code could use a bit more black.' && exit 1)
      - run:
          name: Run tests
          command: |
           /home/circleci/.local/bin/coverage run tests/test_xlson.py
      - run:
          name: upload coverage report
          command: |
            /home/circleci/.local/bin/coverage xml
            /home/circleci/.local/bin/codecov --required -X search gcov pycov -f coverage.xml
      - run:
          name: Building artifacts
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - store_artifacts:
          path: dist/
          destination: ./
      - save_cache:
          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.local/lib
            - /home/circleci/.local/bin
  py-3.6:
    <<: *build-template
    docker:
      - image: circleci/python:3.6
workflows:
  version: 2
  build:
    jobs:
      - py-3.7
      - py-3.6
